
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import React from "react";

export const previews = {
  "demos/components/core/react/button/default": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/default")),
    code: [{"title":"default.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\n\r\nexport default function Demo() {\r\n  return <Button>Button</Button>;\r\n}\r\n"}]
  },
  "demos/components/core/react/button/variants": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/variants")),
    code: [{"title":"variants.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\n\r\nconst variants = [\r\n  \"default\",\r\n  \"secondary\",\r\n  \"outline\",\r\n  \"quiet\",\r\n  \"success\",\r\n  \"warning\",\r\n  \"danger\",\r\n  \"accent\",\r\n] as const;\r\n\r\nexport default function Demo() {\r\n  return (\r\n    <div className=\"grid grid-cols-4 gap-2\">\r\n      {variants.map((variant) => (\r\n        <Button key={variant} variant={variant}>\r\n          {variant}\r\n        </Button>\r\n      ))}\r\n    </div>\r\n  );\r\n}\r\n"}]
  },
  "demos/components/core/react/button/sizes": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/sizes")),
    code: [{"title":"sizes.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\n\r\nexport default function Demo() {\r\n  return (\r\n    <div className=\"flex w-full items-center justify-center gap-4\">\r\n      <Button size=\"sm\">Button</Button>\r\n      <Button size=\"md\">Button</Button>\r\n      <Button size=\"lg\">Button</Button>\r\n    </div>\r\n  );\r\n}\r\n"}]
  },
  "demos/components/core/react/button/shapes": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/shapes")),
    code: [{"title":"shapes.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\nimport { UploadIcon } from \"@/lib/icons\";\r\n\r\nexport default function Demo() {\r\n  return (\r\n    <div className=\"flex items-center justify-center gap-4\">\r\n      <Button size=\"sm\" shape=\"square\" aria-label=\"upload\">\r\n        <UploadIcon />\r\n      </Button>\r\n      <Button size=\"md\" shape=\"square\" aria-label=\"upload\">\r\n        <UploadIcon />\r\n      </Button>\r\n      <Button size=\"lg\" shape=\"square\" aria-label=\"upload\">\r\n        <UploadIcon />\r\n      </Button>\r\n      <Button size=\"sm\" shape=\"circle\" aria-label=\"upload\">\r\n        <UploadIcon />\r\n      </Button>\r\n      <Button size=\"md\" shape=\"circle\" aria-label=\"upload\">\r\n        <UploadIcon />\r\n      </Button>\r\n      <Button size=\"lg\" shape=\"circle\" aria-label=\"upload\">\r\n        <UploadIcon />\r\n      </Button>\r\n    </div>\r\n  );\r\n}\r\n"}]
  },
  "demos/components/core/react/button/prefix-and-suffix": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/prefix-and-suffix")),
    code: [{"title":"prefix-and-suffix.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\nimport { UploadIcon } from \"@/lib/icons\";\r\n\r\nexport default function Demo() {\r\n  return (\r\n    <div className=\"flex items-center gap-2\">\r\n      <Button prefix={<UploadIcon />}>Upload</Button>\r\n      <Button suffix={<UploadIcon />}>Upload</Button>\r\n    </div>\r\n  );\r\n}\r\n"}]
  },
  "demos/components/core/react/button/loading": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/loading")),
    code: [{"title":"loading.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\n\r\nexport default function Demo() {\r\n  return (\r\n    <div className=\"flex w-full items-center justify-center gap-2\">\r\n      <Button size=\"sm\" isLoading>\r\n        Button\r\n      </Button>\r\n      <Button size=\"md\" isLoading>\r\n        Button\r\n      </Button>\r\n      <Button size=\"lg\" isLoading>\r\n        Button\r\n      </Button>\r\n    </div>\r\n  );\r\n}\r\n"}]
  },
  "demos/components/core/react/button/disabled": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/disabled")),
    code: [{"title":"disabled.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\n\r\nexport default function Demo() {\r\n  return <Button isDisabled>Button</Button>;\r\n}\r\n"}]
  },
  "demos/components/core/react/button/link-button": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/link-button")),
    code: [{"title":"link-button.tsx","code":"import { Button } from \"@/lib/components/core/default/react/button\";\r\nimport { LogInIcon } from \"@/lib/icons\";\r\n\r\nexport default function Demo() {\r\n  return (\r\n    <Button href=\"/login\" prefix={<LogInIcon />} target=\"_blank\">\r\n      Login\r\n    </Button>\r\n  );\r\n}\r\n"}]
  },
  "demos/components/core/vue/button/default": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/default")),
    code: [{"title":"default.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\n</script>\r\n\r\n<template>\r\n  <Button>Button</Button>\r\n</template>"}]
  },
  "demos/components/core/vue/button/variants": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/variants")),
    code: [{"title":"variants.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\n\r\nconst variants = [\r\n  \"default\",\r\n  \"secondary\",\r\n  \"outline\",\r\n  \"quiet\",\r\n  \"success\",\r\n  \"warning\",\r\n  \"danger\",\r\n  \"accent\",\r\n] as const;\r\n</script>\r\n\r\n\r\n<template>\r\n  <div class=\"grid grid-cols-4 gap-2\">\r\n    <Button v-for=\"variant in variants\" :key=\"variant\" :variant=\"variant\">\r\n      {{ variant }}\r\n    </Button>\r\n  </div>\r\n</template>\r\n"}]
  },
  "demos/components/core/vue/button/sizes": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/sizes")),
    code: [{"title":"sizes.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\n</script>\r\n\r\n<template>\r\n    <div className=\"flex w-full items-center justify-center gap-4\">\r\n      <Button size=\"sm\">Button</Button>\r\n      <Button size=\"md\">Button</Button>\r\n      <Button size=\"lg\">Button</Button>\r\n    </div>\r\n</template>"}]
  },
  "demos/components/core/vue/button/shapes": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/shapes")),
    code: [{"title":"shapes.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\nimport { UploadIcon } from \"@/lib/icons\";\r\n</script>\r\n\r\n<template>\r\n  <div className=\"flex items-center justify-center gap-4\">\r\n    <Button size=\"sm\" shape=\"square\" aria-label=\"upload\">\r\n      <UploadIcon />\r\n    </Button>\r\n    <Button size=\"md\" shape=\"square\" aria-label=\"upload\">\r\n      <UploadIcon />\r\n    </Button>\r\n    <Button size=\"lg\" shape=\"square\" aria-label=\"upload\">\r\n      <UploadIcon />\r\n    </Button>\r\n    <Button size=\"sm\" shape=\"circle\" aria-label=\"upload\">\r\n      <UploadIcon />\r\n    </Button>\r\n    <Button size=\"md\" shape=\"circle\" aria-label=\"upload\">\r\n      <UploadIcon />\r\n    </Button>\r\n    <Button size=\"lg\" shape=\"circle\" aria-label=\"upload\">\r\n      <UploadIcon />\r\n    </Button>\r\n  </div>\r\n</template>"}]
  },
  "demos/components/core/vue/button/prefix-and-suffix": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/prefix-and-suffix")),
    code: [{"title":"prefix-and-suffix.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\nimport { UploadIcon } from \"@/lib/icons\";\r\n</script>\r\n\r\n<template>\r\n  <div className=\"flex items-center gap-2\">\r\n    <Button :prefix=\"UploadIcon\">\r\n      Button\r\n    </Button>\r\n    <Button :suffix=\"UploadIcon\">\r\n      Button\r\n    </Button>\r\n  </div>\r\n</template>\r\n"}]
  },
  "demos/components/core/vue/button/loading": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/loading")),
    code: [{"title":"loading.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\nimport { ref } from 'vue';\r\nconst someVariable = ref(5);\r\n</script>\r\n\r\n<template>\r\n  <div className=\"flex w-full items-center justify-center gap-2\">\r\n    <Button size=\"sm\" :isLoading=\"someVariable === 5\">\r\n      Button\r\n    </Button>\r\n    <Button size=\"md\" isLoading>\r\n      Button\r\n    </Button>\r\n    <Button size=\"lg\" isLoading>\r\n      Button\r\n    </Button>\r\n  </div>\r\n</template>\r\n"}]
  },
  "demos/components/core/vue/button/disabled": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/disabled")),
    code: [{"title":"disabled.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\nimport { ref } from 'vue';\r\nconst someVariable = ref(5);\r\n</script>\r\n\r\n<template>\r\n  <Button :isDisabled=\"someVariable === 5\">Button</Button>\r\n</template>\r\n"}]
  },
  "demos/components/core/vue/button/link-button": {
    component: React.lazy(() => import("@/lib/demos/components/core/react/button/link-button")),
    code: [{"title":"link-button.vue","code":"<script setup lang=\"ts\">\r\nimport Button from '@/lib/components/core/default/vue/button.vue';\r\nimport { LinkIcon } from '@/lib/icons';\r\n</script>\r\n\r\n<template>\r\n  <Button href=\"/login\" target=\"_blank\" :prefix=\"LinkIcon\">\r\n    Login\r\n  </Button>\r\n</template>"}]
  },
};
