
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  "nav": [
    {
      "title": "Getting Started",
      "slug": "docs",
      "items": [
        {
          "title": "Installation",
          "href": "/docs/installation"
        }
      ]
    },
    {
      "title": "Components",
      "slug": "components",
      "items": [
        {
          "title": "React",
          "href": "/components/react",
          "items": [
            {
              "title": "Buttons",
              "href": "/components/react/buttons",
              "items": [
                {
                  "title": "Button",
                  "href": "/components/react/buttons/button"
                }
              ]
            }
          ]
        },
        {
          "title": "Vue",
          "href": "/components/vue",
          "items": [
            {
              "title": "Buttons",
              "href": "/components/vue/buttons",
              "items": [
                {
                  "title": "Button",
                  "href": "/components/vue/buttons/button"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};
